 version: 2
 jobs:
   one:
     build:
       docker:
         - image: circleci/ruby:2.4.1
       steps:
         - checkout
         - run: echo "build named one"
         - run: sleep 10
   two:
     build:
       docker:
         - image: circleci/ruby:2.4.1
       steps:
         - checkout
         - run: "hello from build nameed two"
         - run: sleep 15
         
 workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two
